---
- name:  removing apache and mysql
  hosts: localhost

  tasks:
  - name: Can we remove Apache2 Web server
    become: true
    apt: pkg=apache2 state=absent 

  tasks:
  - name: Can we install MySQL
    become: true
    apt: pkg=mysql-server state=absent 

