---
- name:  installing apache and mysql
  hosts: localhost

  tasks:
  - name: Can we install Apache2 Web server
    become: true
    apt: pkg=apache2 state=latest update_cache=true

  tasks:
  - name: Can we install MySQL
    become: true
    apt: pkg=mysql-server state=latest update_cache=true

