- name:  installing ngnix
  hosts: servers

  tasks:
  - name: Install ngnix
    become: true
    apt: name=nginx
  - name: Update the cache
    become: true
    apt:
        update_cache: yes

  - name: Restart Jenkins
    become: true
    service: name=nginx  state=restarted
